### ISSUE TITLE
can't open 'sgg.lib'

### ISSUE THREAD

**Issue by SacredTravis** [cgaueb/sgg#6]
I was setting up the library but there is no sgg.lib file and the compiler told me that it can not open it. Where is this file?

**Comment by ViNeek** [comment]
Please follow the respective guides for building and using SGG found in the library's documentation.

[https://cgaueb.github.io/sgg/pages.html](https://cgaueb.github.io/sgg/pages.html)

**Comment by SacredTravis** [comment]
@ViNeek  I followed this guide but in the files the sgg.lib and sggd.lib does not exist. At first I thought that maybe they do not need to exist but the compiler wants them.

**Comment by ViNeek** [comment]
Step 2 of the guide specifies that to build the library simply double click on the build_sgg_x64.bat. This script builds both a Release (sgg.lib) and a Debug (sggd.lib) version of the library. The resulting libraries are stored in the **lib** folder.

If the files are not properly created in the lib folder then there is probably something wrong with your Visual Studio installation.

Please try to run the script from a console in order to see what is wrong. 

We need more specific information to help you. If you are using the library as part of this year's undergraduate C++ class porject at AUEB. you should contact the class's assistants directly for better support.

**Comment by SacredTravis** [comment]
![image](https://user-images.githubusercontent.com/77144982/208296767-d2716fbb-2505-4e1d-8c96-2cb520cba877.png)
I have already done that and the only libraries it created for me was those. @ViNeek

**Comment by ViNeek** [comment]
Something is wrong with your Visual Studio installation. I cannot help you from here about that. You should run the script from a console to see what is printed and why compilation fails.

**Comment by SacredTravis** [comment]
@ViNeek I deleted and reinstalled Visual Studio and it still does not work. I think I am doing something wrong with the library. I downloaded all the files in https://github.com/cgaueb/sgg and I extracted the files in a folder at desktop. After that I try to run the build_sgg_x64.bat the only thing it does is that for half a second a console opens and closes.

**Comment by ViNeek** [comment]
The library has all the required parts included. Are you installing the Visual Stduio in a NON-default location on your hard drive? In order to get more information about what is failing, you need to run the script from a console window.

- Open a win32 command line (at the start menu, search for cmd)
- Change directory (cd) to where you have unzipped the library
- Execute build_sgg_x64.bat

Please take a screenshot of the resulting messages and post it here so we can have more information about what is going wrong.

**Comment by SacredTravis** [comment]
@ViNeek Yes I have installed Visual studio at the D drive not the c. 
The console shows that
![image](https://user-images.githubusercontent.com/77144982/208643238-7500f4af-33ed-4e52-8a43-f54f3ec1a03a.png)

The console says that I do not have the right visual studio but I have the Visual Studio 2022
![image](https://user-images.githubusercontent.com/77144982/208643719-9f5adf94-6ac0-4f72-b602-f0437abd7c17.png)

**Comment by ViNeek** [comment]
Please change the following lines in the build_sgg_x64.bat script to use the path that you installed Visual Studio in.

set STUDIO_PATH=C:\Program Files (x86)\Microsoft Visual Studio
set STUDIO_PATH_X64=C:\Program Files\Microsoft Visual Studio

and rerun the script.

Same thing for the demo script.

**Comment by SacredTravis** [comment]
@ViNeek ![image](https://user-images.githubusercontent.com/77144982/208652305-e9f229cb-f8f8-4374-8e71-6a612df132b5.png)

How can I know what path to add? I ask because you have different paths in the STUDIO_PATH and STUDIO_PATH_X64. My Visual studio is in D:\VS2022 and in the C:\Program Files (x86) there is this 
![image](https://user-images.githubusercontent.com/77144982/208653119-aeddc54b-0d60-415b-b64b-1fb679b9d986.png)

Do I have to set specific files ? Because when I put in both lines the  D:\VS2022 path it still does not work.

**Comment by ViNeek** [comment]
You need to construct the path so that this line forms a valid path to the vcvars64.bat script

call "%STUDIO_PATH%\%STUDIO_VERSION%\%STUDIO_EDITION%\VC\Auxiliary\Build\vcvars64.bat"

Also don't forget to change line 20 -> set STUDIO_PATH=C:\Program Files\Microsoft Visual Studio to your PATH.

You can also reinstall VS2022 in C:. Since you have not followed the default installation it is your responsibility to fix the paths.

**Comment by SacredTravis** [comment]
Okay thanks! I just removed the if statements and I manually set the version. I also did what you told me. Huge thanks again! @ViNeek
